routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/forgot-password', function () {
  return view('auth.forgot-password');
})->middleware('guest')->name('password.request');
Route::get('/reset-password/{token}', function ($token) {
  return view('auth.reset-password', ['token' => $token]);
})->middleware('guest')->name('password.reset');
Auth::routes();
Route::get('/admin/login', [App\Http\Controllers\HomeController::class, 'adminLogin'])->name('admin.login');
Route::post('/admin/login/request', [App\Http\Controllers\HomeController::class, 'adminLoginRequest'])->name('admin.login.request');
Route::post('/admin/logout', [App\Http\Controllers\HomeController::class, 'adminLogout'])->name('admin.logut');
Route::middleware(['admin.auth'])->group( function () {
  Route::group(['prefix' => 'admin'], function(){

    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('admin');
    Route::post('/admin-edit-profile', [App\Http\Controllers\HomeController::class, 'adminEditProfile'])->name('admin.edit.profile');
    Route::post('/admin-edit-password', [App\Http\Controllers\HomeController::class, 'adminEditPassword'])->name('admin.edit.password');
    Route::resource('generalSettings', App\Http\Controllers\generalSettingsController::class);
    Route::resource('resturentAddresses', App\Http\Controllers\ResturentAddressController::class);
    Route::get('resturentAddresses-add/{id?}', [App\Http\Controllers\ResturentAddressController::class,'addResturentAddress'])->name('resturentAddresses.add-address');

    Route::post('save-address-of_resturent', [App\Http\Controllers\ResturentAddressController::class,'saveResturentAddress'])->name('resturentAddresses.save-address');

    Route::resource('deliveryChargesDetails', App\Http\Controllers\deliveryChargesDetailsController::class);
    Route::resource('orders', App\Http\Controllers\ordersController::class);
    Route::resource('sliders', App\Http\Controllers\sliderController::class);
    Route::resource('ourStories', App\Http\Controllers\ourStoryController::class);
    Route::resource('galleries', App\Http\Controllers\GalleryController::class);
    Route::resource('cms', App\Http\Controllers\CmsController::class);
    Route::resource('smsSettings', App\Http\Controllers\SmsSettingController::class);
    Route::resource('messageTemplatings', App\Http\Controllers\MessageTemplatingController::class);
    Route::resource('tableReservations', App\Http\Controllers\TableReservationController::class);
    Route::get('page-builder', [App\Http\Controllers\PageBuilderController::class,'index'])->name('page-builder');
    Route::resource('categories', App\Http\Controllers\categoryController::class);
    Route::post('save.php', [App\Http\Controllers\PageBuilderController::class,'save']);
    Route::post('upload.php', [App\Http\Controllers\PageBuilderController::class,'upload']);
    Route::get('scan.php', [App\Http\Controllers\PageBuilderController::class,'scan']);
    Route::resource('pages', App\Http\Controllers\PagesController::class);
    Route::resource('products', App\Http\Controllers\ProductsController::class);
    Route::resource('productMetas', App\Http\Controllers\product_metaController::class);
    Route::post('add-attribute', [App\Http\Controllers\product_metaController::class,'addAttribute'])->name('add-attribute');
    Route::post('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes'])->name('fetch-attributes');

    Route::get('add-child-product-meta/{id_meta}', [App\Http\Controllers\product_metaController::class,'addChildProductMeta'])->name('add-child-product-meta');
    Route::post('delete-product-meta-attribute/{id?}', [App\Http\Controllers\product_metaController::class,'deleteProductMetaAttribute'])->name('delete-product-meta-attribute');
    Route::post('update-attribute', [App\Http\Controllers\product_metaController::class,'updateAttributeForAdmin'])->name('update-attribute');
    Route::resource('resturentTimings', App\Http\Controllers\ResturentTimingsController::class);
    Route::resource('restaurantTimingsSpecifics', App\Http\Controllers\RestaurantTimingsSpecificController::class);
    Route::resource('paymentMethods', App\Http\Controllers\PaymentMethodsController::class);
    Route::resource('reviews', App\Http\Controllers\ReviewsController::class);
    Route::resource('users', App\Http\Controllers\UsersController::class);
    Route::get('users/orders/{id}', [App\Http\Controllers\UsersController::class,'showOrders'])->name('users.view.orders');
    Route::get('users/carts/{id}', [App\Http\Controllers\UsersController::class,'showCarts'])->name('users.view.carts');
    Route::resource('tableCategories', App\Http\Controllers\TableCategoriesController::class);
    Route::resource('customerReservations', App\Http\Controllers\CustomerReservationsController::class);

    Route::resource('locations', App\Http\Controllers\LocationsController::class);


    Route::resource('locationsAttributes', App\Http\Controllers\LocationsAttributesController::class);
    Route::get('reset-cache', [App\Http\Controllers\DashboardController::class,'resetCache'])->name('reset-cache');
  });
});


Route::get('my-account', [App\Http\Controllers\HomeController::class, 'myAccount'])->name('user.my-account');
Route::get('change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('user.change.password');
Route::post('user-details-update', [App\Http\Controllers\HomeController::class, 'userDetailsUpdate'])->name('user-details-update');
Route::post('user-registration', [App\Http\Controllers\HomeController::class, 'userRegister'])->name('user-registration');
Route::post('user-password-update', [App\Http\Controllers\HomeController::class, 'userPasswordUpdate'])->name('user.password.update');

Route::get('order-history', [App\Http\Controllers\HomeController::class, 'orderHistory'])->name('user.order.history');
Route::get('addresses', [App\Http\Controllers\HomeController::class, 'userAddresses'])->name('user.addresses');

Route::get('/', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('page/{name}', [App\Http\Controllers\PageBuilderController::class,'getPage'])->name('pages');

Route::get('order-online', [App\Http\Controllers\HomeController::class,'OrderOnline'])->name('order-online');
Route::get('payment-confirm', [App\Http\Controllers\HomeController::class,'paymentConfirm'])->name('payment-confirm');

Route::get('thank-you', [App\Http\Controllers\HomeController::class,'thankYou'])->name('thank-you');
Route::get('contact-us', [App\Http\Controllers\HomeController::class,'contactUs'])->name('contact-us');
Route::get('checkout/{reference?}', [App\Http\Controllers\HomeController::class,'checkout'])->name('checkout');
Route::post('place-order', [App\Http\Controllers\HomeController::class,'placeOrder'])->name('web.place-order');
Route::get('reviews/{ratings?}', [App\Http\Controllers\HomeController::class,'reviews'])->name('reviews');

Route::get('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes']);


Route::resource('notifications', App\Http\Controllers\NotificationsController::class);
Route::post('stream-check-out', [App\Http\Controllers\PaymentMethodsController::class,'cardStreamCallback']);
Route::post('get-cart-id', [App\Http\Controllers\HomeController::class,'getCartId'])->name('get-cart-id');


Route::resource('vouchers', App\Http\Controllers\VouchersController::class);
Route::get('download/pdf/{reference}', [App\Http\Controllers\HomeController::class,'downloadPdf'])->name('downloadPdf');
Route::get('save/pdf/{reference}', [App\Http\Controllers\HomeController::class,'savePdf'])->name('savePdf');
Route::get('view/pdf/{reference}', [App\Http\Controllers\HomeController::class,'viewPdf'])->name('viewPdf');


Route::get('reservations',[App\Http\Controllers\HomeController::class,'reservations'])->name('reservations');
Route::get('locations',[App\Http\Controllers\HomeController::class,'locations'])->name('locations');
Route::get('locations/{id}',[App\Http\Controllers\HomeController::class,'locations'])->name('locations.attributes');











Route::resource('holdCarts', App\Http\Controllers\HoldCartsController::class);


Route::resource('caosGenralSettings', App\Http\Controllers\CaosGenralSettingsController::class);

app/Models/MessageTemplating.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class MessageTemplating
 * @package App\Models
 * @version February 7, 2022, 9:43 pm UTC
 *
 * @property string $template_slug
 * @property string $description
 * @property integer $status
 */
class MessageTemplating extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'message_templating';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'template_slug',
        'description',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'template_slug' => 'string',
        'status' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'template_slug' => 'required',
        'description' => 'required'
    ];

    
}

app/Http/Controllers/MessageTemplatingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMessageTemplatingRequest;
use App\Http\Requests\UpdateMessageTemplatingRequest;
use App\Repositories\MessageTemplatingRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class MessageTemplatingController extends AppBaseController
{
    /** @var  MessageTemplatingRepository */
    private $messageTemplatingRepository;

    public function __construct(MessageTemplatingRepository $messageTemplatingRepo)
    {
        $this->messageTemplatingRepository = $messageTemplatingRepo;
    }

    /**
     * Display a listing of the MessageTemplating.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $messageTemplatings = $this->messageTemplatingRepository->paginate(10);

        return view('message_templatings.index')
            ->with('messageTemplatings', $messageTemplatings);
    }

    /**
     * Show the form for creating a new MessageTemplating.
     *
     * @return Response
     */
    public function create()
    {
        return view('message_templatings.create');
    }

    /**
     * Store a newly created MessageTemplating in storage.
     *
     * @param CreateMessageTemplatingRequest $request
     *
     * @return Response
     */
    public function store(CreateMessageTemplatingRequest $request)
    {
        $input = $request->all();

        $messageTemplating = $this->messageTemplatingRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/messageTemplatings.singular')]));

        return redirect(route('messageTemplatings.index'));
    }

    /**
     * Display the specified MessageTemplating.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $messageTemplating = $this->messageTemplatingRepository->find($id);

        if (empty($messageTemplating)) {
            Flash::error(__('messages.not_found', ['model' => __('models/messageTemplatings.singular')]));

            return redirect(route('messageTemplatings.index'));
        }

        return view('message_templatings.show')->with('messageTemplating', $messageTemplating);
    }

    /**
     * Show the form for editing the specified MessageTemplating.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $messageTemplating = $this->messageTemplatingRepository->find($id);

        if (empty($messageTemplating)) {
            Flash::error(__('messages.not_found', ['model' => __('models/messageTemplatings.singular')]));

            return redirect(route('messageTemplatings.index'));
        }

        return view('message_templatings.edit')->with('messageTemplating', $messageTemplating);
    }

    /**
     * Update the specified MessageTemplating in storage.
     *
     * @param int $id
     * @param UpdateMessageTemplatingRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMessageTemplatingRequest $request)
    {
        $messageTemplating = $this->messageTemplatingRepository->find($id);

        if (empty($messageTemplating)) {
            Flash::error(__('messages.not_found', ['model' => __('models/messageTemplatings.singular')]));

            return redirect(route('messageTemplatings.index'));
        }

        $messageTemplating = $this->messageTemplatingRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/messageTemplatings.singular')]));

        return redirect(route('messageTemplatings.index'));
    }

    /**
     * Remove the specified MessageTemplating from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $messageTemplating = $this->messageTemplatingRepository->find($id);

        if (empty($messageTemplating)) {
            Flash::error(__('messages.not_found', ['model' => __('models/messageTemplatings.singular')]));

            return redirect(route('messageTemplatings.index'));
        }

        $this->messageTemplatingRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/messageTemplatings.singular')]));

        return redirect(route('messageTemplatings.index'));
    }
}

resources/views/message_templatings/create.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.add_new') @lang('models/messageTemplatings.singular')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/messageTemplatings.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('messageTemplatings.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'messageTemplatings.store']) !!}
                                    <div class="row">
                                        @include('message_templatings.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/message_templatings/edit.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.edit') @lang('models/messageTemplatings.singular')
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/messageTemplatings.singular')</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('messageTemplatings.index') }}"  class="btn btn-primary">@lang('crud.back')</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($messageTemplating, ['route' => ['messageTemplatings.update', $messageTemplating->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('message_templatings.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/message_templatings/fields.blade.php
<!-- Template Slug Field -->
<div class="form-group col-sm-6">
    {!! Form::label('template_slug', __('models/messageTemplatings.fields.template_slug').':') !!}
    {!! Form::text('template_slug', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', __('models/messageTemplatings.fields.description').':') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', __('models/messageTemplatings.fields.status').':') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('status', 0) !!}
        {!! Form::checkbox('status', '1', null) !!}
    </label>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('messageTemplatings.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>

resources/views/message_templatings/index.blade.php
@extends('layouts.app')
@section('title')
     @lang('models/messageTemplatings.plural')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/messageTemplatings.plural')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('messageTemplatings.create')}}" class="btn btn-primary form-btn">@lang('crud.add_new')<i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('message_templatings.table')
            </div>
       </div>
   </div>
    
        @include('stisla-templates::common.paginate', ['records' => $messageTemplatings])

    </section>
@endsection

resources/views/message_templatings/show.blade.php
@extends('layouts.app')
@section('title')
    @lang('models/messageTemplatings.singular')  @lang('crud.details') 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>@lang('models/messageTemplatings.singular') @lang('crud.details')</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('messageTemplatings.index') }}"
                 class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('message_templatings.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/message_templatings/show_fields.blade.php
<!-- Template Slug Field -->
<div class="form-group">
    {!! Form::label('template_slug', __('models/messageTemplatings.fields.template_slug').':') !!}
    <p>{{ $messageTemplating->template_slug }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', __('models/messageTemplatings.fields.description').':') !!}
    <p>{{ $messageTemplating->description }}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', __('models/messageTemplatings.fields.status').':') !!}
    <p>{{ $messageTemplating->status }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/messageTemplatings.fields.created_at').':') !!}
    <p>{{ $messageTemplating->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', __('models/messageTemplatings.fields.updated_at').':') !!}
    <p>{{ $messageTemplating->updated_at }}</p>
</div>

resources/views/message_templatings/table.blade.php
<div class="table-responsive">
    <table class="table" id="messageTemplatings-table">
        <thead>
            <tr>
                <th>@lang('models/messageTemplatings.fields.template_slug')</th>
        <th>@lang('models/messageTemplatings.fields.description')</th>
        <th>@lang('models/messageTemplatings.fields.status')</th>
                <th colspan="3">@lang('crud.action')</th>
            </tr>
        </thead>
        <tbody>
        @foreach($messageTemplatings as $messageTemplating)
            <tr>
                       <td>{{ $messageTemplating->template_slug }}</td>
            <td>{{ $messageTemplating->description }}</td>
            <td>{{ $messageTemplating->status }}</td>
                       <td class=" text-center">
                           {!! Form::open(['route' => ['messageTemplatings.destroy', $messageTemplating->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('messageTemplatings.show', [$messageTemplating->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('messageTemplatings.edit', [$messageTemplating->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                   </tr>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>