routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/forgot-password', function () {
  return view('auth.forgot-password');
})->middleware('guest')->name('password.request');
Route::get('/reset-password/{token}', function ($token) {
  return view('auth.reset-password', ['token' => $token]);
})->middleware('guest')->name('password.reset');
Auth::routes();
Route::get('/admin/login', [App\Http\Controllers\HomeController::class, 'adminLogin'])->name('admin.login');
Route::post('/admin/login/request', [App\Http\Controllers\HomeController::class, 'adminLoginRequest'])->name('admin.login.request');
Route::post('/admin/logout', [App\Http\Controllers\HomeController::class, 'adminLogout'])->name('admin.logut');
Route::middleware(['admin.auth'])->group( function () {
  Route::group(['prefix' => 'admin'], function(){

    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('admin');
    Route::post('/admin-edit-profile', [App\Http\Controllers\HomeController::class, 'adminEditProfile'])->name('admin.edit.profile');
    Route::post('/admin-edit-password', [App\Http\Controllers\HomeController::class, 'adminEditPassword'])->name('admin.edit.password');
    Route::resource('generalSettings', App\Http\Controllers\generalSettingsController::class);
    Route::resource('resturentAddresses', App\Http\Controllers\ResturentAddressController::class);
    Route::get('resturentAddresses-add/{id?}', [App\Http\Controllers\ResturentAddressController::class,'addResturentAddress'])->name('resturentAddresses.add-address');

    Route::post('save-address-of_resturent', [App\Http\Controllers\ResturentAddressController::class,'saveResturentAddress'])->name('resturentAddresses.save-address');

    Route::resource('deliveryChargesDetails', App\Http\Controllers\deliveryChargesDetailsController::class);
    Route::resource('orders', App\Http\Controllers\ordersController::class);
    Route::resource('sliders', App\Http\Controllers\sliderController::class);
    Route::resource('ourStories', App\Http\Controllers\ourStoryController::class);
    Route::resource('galleries', App\Http\Controllers\GalleryController::class);
    Route::resource('cms', App\Http\Controllers\CmsController::class);
    Route::resource('smsSettings', App\Http\Controllers\SmsSettingController::class);
    Route::resource('messageTemplatings', App\Http\Controllers\MessageTemplatingController::class);
    Route::resource('tableReservations', App\Http\Controllers\TableReservationController::class);
    Route::get('page-builder', [App\Http\Controllers\PageBuilderController::class,'index'])->name('page-builder');
    Route::resource('categories', App\Http\Controllers\categoryController::class);
    Route::post('save.php', [App\Http\Controllers\PageBuilderController::class,'save']);
    Route::post('upload.php', [App\Http\Controllers\PageBuilderController::class,'upload']);
    Route::get('scan.php', [App\Http\Controllers\PageBuilderController::class,'scan']);
    Route::resource('pages', App\Http\Controllers\PagesController::class);
    Route::resource('products', App\Http\Controllers\ProductsController::class);
    Route::resource('productMetas', App\Http\Controllers\product_metaController::class);
    Route::post('add-attribute', [App\Http\Controllers\product_metaController::class,'addAttribute'])->name('add-attribute');
    Route::post('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes'])->name('fetch-attributes');

    Route::get('add-child-product-meta/{id_meta}', [App\Http\Controllers\product_metaController::class,'addChildProductMeta'])->name('add-child-product-meta');
    Route::post('delete-product-meta-attribute/{id?}', [App\Http\Controllers\product_metaController::class,'deleteProductMetaAttribute'])->name('delete-product-meta-attribute');
    Route::post('update-attribute', [App\Http\Controllers\product_metaController::class,'updateAttributeForAdmin'])->name('update-attribute');
    Route::resource('resturentTimings', App\Http\Controllers\ResturentTimingsController::class);
    Route::resource('restaurantTimingsSpecifics', App\Http\Controllers\RestaurantTimingsSpecificController::class);
    Route::resource('paymentMethods', App\Http\Controllers\PaymentMethodsController::class);
    Route::resource('reviews', App\Http\Controllers\ReviewsController::class);
    Route::resource('users', App\Http\Controllers\UsersController::class);
    Route::get('users/orders/{id}', [App\Http\Controllers\UsersController::class,'showOrders'])->name('users.view.orders');
    Route::get('users/carts/{id}', [App\Http\Controllers\UsersController::class,'showCarts'])->name('users.view.carts');
    Route::resource('tableCategories', App\Http\Controllers\TableCategoriesController::class);
    Route::resource('customerReservations', App\Http\Controllers\CustomerReservationsController::class);

    Route::resource('locations', App\Http\Controllers\LocationsController::class);


    Route::resource('locationsAttributes', App\Http\Controllers\LocationsAttributesController::class);
    Route::get('reset-cache', [App\Http\Controllers\DashboardController::class,'resetCache'])->name('reset-cache');
  });
});


Route::get('my-account', [App\Http\Controllers\HomeController::class, 'myAccount'])->name('user.my-account');
Route::get('change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('user.change.password');
Route::post('user-details-update', [App\Http\Controllers\HomeController::class, 'userDetailsUpdate'])->name('user-details-update');
Route::post('user-registration', [App\Http\Controllers\HomeController::class, 'userRegister'])->name('user-registration');
Route::post('user-password-update', [App\Http\Controllers\HomeController::class, 'userPasswordUpdate'])->name('user.password.update');

Route::get('order-history', [App\Http\Controllers\HomeController::class, 'orderHistory'])->name('user.order.history');
Route::get('addresses', [App\Http\Controllers\HomeController::class, 'userAddresses'])->name('user.addresses');

Route::get('/', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('page/{name}', [App\Http\Controllers\PageBuilderController::class,'getPage'])->name('pages');

Route::get('order-online', [App\Http\Controllers\HomeController::class,'OrderOnline'])->name('order-online');
Route::get('payment-confirm', [App\Http\Controllers\HomeController::class,'paymentConfirm'])->name('payment-confirm');

Route::get('thank-you', [App\Http\Controllers\HomeController::class,'thankYou'])->name('thank-you');
Route::get('contact-us', [App\Http\Controllers\HomeController::class,'contactUs'])->name('contact-us');
Route::get('checkout/{reference?}', [App\Http\Controllers\HomeController::class,'checkout'])->name('checkout');
Route::post('place-order', [App\Http\Controllers\HomeController::class,'placeOrder'])->name('web.place-order');
Route::get('reviews/{ratings?}', [App\Http\Controllers\HomeController::class,'reviews'])->name('reviews');

Route::get('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes']);


Route::resource('notifications', App\Http\Controllers\NotificationsController::class);
Route::post('stream-check-out', [App\Http\Controllers\PaymentMethodsController::class,'cardStreamCallback']);
Route::post('get-cart-id', [App\Http\Controllers\HomeController::class,'getCartId'])->name('get-cart-id');


Route::resource('vouchers', App\Http\Controllers\VouchersController::class);
Route::get('download/pdf/{reference}', [App\Http\Controllers\HomeController::class,'downloadPdf'])->name('downloadPdf');
Route::get('save/pdf/{reference}', [App\Http\Controllers\HomeController::class,'savePdf'])->name('savePdf');
Route::get('view/pdf/{reference}', [App\Http\Controllers\HomeController::class,'viewPdf'])->name('viewPdf');


Route::get('reservations',[App\Http\Controllers\HomeController::class,'reservations'])->name('reservations');
Route::get('locations',[App\Http\Controllers\HomeController::class,'locations'])->name('locations');
Route::get('locations/{id}',[App\Http\Controllers\HomeController::class,'locations'])->name('locations.attributes');











Route::resource('holdCarts', App\Http\Controllers\HoldCartsController::class);


Route::resource('caosGenralSettings', App\Http\Controllers\CaosGenralSettingsController::class);

app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Data\Models\ProductGroups;
use App\Data\Models\Products;
use App\Data\Models\ProductSizes;
use App\Models\ProductMetasBridge;
use App\Data\Repositories\ProductRepository;
use App\Repositories\ProductsRepository as NewProductRepository;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Validator;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends Controller
{
    protected $_repository;
    const PER_PAGE = 10;

    public function __construct(ProductRepository $repository)
    {
        $this->_repository = $repository;
    }

    public function index(Request $request)
    {
        $requestData = $request->all();
        $pagination = !empty($requestData['pagination']) ? $requestData['pagination'] : false;
        $per_page = self::PER_PAGE;
        $data = $this->_repository->findByAll($pagination,$per_page,$requestData);
        $output = [
            'data' => $data['data'],
            'pagination' => !empty($data['pagination']) ? $data['pagination'] : false,
            'message' => "Categories Retrieved Successfully",
        ];
        return response()->json($output, Response::HTTP_OK);
    }




    public function store(Request $request ) {

        $requestData = $request->all();
        Cache::flush();

        $validator =  Validator::make($requestData, [
            'name' => 'required',
            'description' => 'required',
            'id_category' => 'required',
            'price' => 'required',
            'inputs.*.size' => 'required',
            'inputs.*.price' => 'required'
        ]);

        if ($validator->fails()) {
            $code = 401;
            $output = ['error' => ['code' => $code, 'message' => $validator->errors()->first()]];
            return response()->json($output, $code);
        }

        $product = new Products();
        $product->fill($request->all());
        $product->save();

        if($product->id) {
            if (count($requestData['inputs']) > 0) {
                foreach ($requestData['inputs'] as $input) {
                    ProductSizes::create(['id_product' => $product->id, 'size' => $input['size'], 'price' => $input['price']]);
                }
            }
        }

        return response()->json([
            'status' => true,
            'created' => true,
            'data' => [
                'id' => $product->id
            ]
        ]);
    }

    public function update(Request $request, $id)
    {
        $requestData = $request->all();
        $requestData['id'] = $id;

        $validator =  Validator::make($requestData, [
            'id' => 'required|exists:products,id',
            'price' => 'required'
        ]);

        if ($validator->fails()) {
            $code = 401;
            $output = ['error' => ['code' => $code, 'message' => $validator->errors()->first()]];
            return response()->json($output, $code);
        }

        $data = $this->_repository->updateRecord($requestData, $id);

        if (count($requestData['inputs']) > 0) {

            Products::find($id)->sizes()->delete();

            foreach ($requestData['inputs'] as $input) {
                ProductSizes::create(['id_product' => $id, 'size' => $input['size'], 'price' => $input['price']]);
            }
        }

        $product = Products::find($id);

        $output = ['data' => $product, 'message' => "Your product has been updated successfully "];
        return response()->json($output, Response::HTTP_OK);
    }

    public function show($id)
    {
       /* if (Cache::has('product-detail-'.$id)) {
            /*Cache::forget('product-detail-'.$id);
            exit;
            $cached = Cache::get('product-detail-'.$id);
            $data = $cached;

        } else { */
            $data = $this->_repository->findById($id);
          //  Cache::store("file")->put('product-detail-'.$id, $data);
        /*}*/

        $output = ['data' => $data, 'message' => __("messages.success")];
        return response()->json($output, Response::HTTP_OK);
    }

    public function downloadAllergy(Request $request)
    {
        $file = url('files/allergy_info.pdf');

        $output = ['data' => $file, 'message' =>  "Success"];
        return response()->json($output, Response::HTTP_OK);
    }

    public function downloadMenu(Request $request)
    {
        $file = url('files/our_menu.pdf');

        $output = ['data' => $file, 'message' =>  "Success"];
        return response()->json($output, Response::HTTP_OK);
    }

    /**
     * Delete resource
     *
     * @param Product Destroy $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id) {

        $product = Products::find($id);

        if($product) {
            $product->groups()->delete();
            $product->sizes()->delete();

            $product->delete();
        }

        return response()->json([
            'status' => true,
            'deleted' => true,
            'data' => []
        ]);
    }

    public function addGroupToProduct(Request $request) {

        $requestData = $request->all();

        $validator =  Validator::make($requestData, [
            'id_group' => 'required',
            'id_product' => 'required',
        ]);

        if ($validator->fails()) {
            $code = 401;
            $output = ['error' => ['code' => $code, 'message' => $validator->errors()->first()]];
            return response()->json($output, $code);
        }

        $product = new ProductGroups();
        $product->fill($request->all());
        $product->save();

        return response()->json([
            'status' => true,
            'deleted' => true,
            'data' => $product
        ]);
    }

    public function removeGroupFromProduct(Request $request) {

        $requestData = $request->all();

        $validator =  Validator::make($requestData, [
            'id_group' => 'required',
            'id_product' => 'required',
        ]);

        if ($validator->fails()) {
            $code = 401;
            $output = ['error' => ['code' => $code, 'message' => $validator->errors()->first()]];
            return response()->json($output, $code);
        }

        ProductMetasBridge::where(['id_product' => $requestData['id_product'], 'id_meta' => $requestData['id_group']])->delete();

        return response()->json([
            'status' => true,
            'deleted' => true
        ]);
    }

    public function getOfferProducts(){
        $offer_products =  DB::table('products')->where('offer',1)->orderBy('id','desc')->get();
        $full_offer_products = [];
        foreach($offer_products as $of_product){
            $full_offer_products[] = app(NewProductRepository::class)->getproductDetails($of_product->id);
        }
        return response()->json([
            'status' => 'success',
            'data' => $full_offer_products
        ]);
    }
    public function getRelatedProducts($id){
        $main_product =  DB::table('products')->where('id',$id)->first();
        $main_product->related_products = [];
        if($main_product->related_product_ids != null){
            $id_products = json_decode($main_product->related_product_ids, TRUE);
            foreach($id_products as $id_product){
                $main_product->related_products[] = app(NewProductRepository::class)->getproductDetails($id_product);
            }

            // $related_product =  DB::table('products')->whereIn('id',$id_products)->get();
            // $main_product->related_products = $related_product;
        }


        return response()->json([
            'status' => 'success',
            'data' => $main_product
        ]);
    }


}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.add_new') @lang('models/products.singular')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/products.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('products.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'products.store', 'files' => true]) !!}
                                    <div class="row">
                                        @include('products.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.edit') @lang('models/products.singular')
@endsection
@section('content')


    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/products.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('products.index') }}"  class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        {{-- @foreach($products->product_metas as $metas)
            @php echo generateGroupsTreeNew($metas); @endphp
        @endforeach --}}
        <div class="content">
                  @include('stisla-templates::common.errors')
                  <div class="section-body">
                     <div class="row">
                         <div class="col-lg-12">
                             <div class="card">
                                 <div class="card-body ">
                                        {!! Form::model($products, ['route' => ['products.update', $products->id], 'method' => 'patch', 'files' => true]) !!}
                                            <div class="row">
                                                @include('products.fields')
                                            </div>

                                        {!! Form::close() !!}
                                </div>
                             </div>
                        </div>
                     </div>
                  </div>
        </div>
  </section>
@endsection

resources/views/products/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/products.fields.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', __('models/products.fields.description').':') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Food Allergy Field -->
<div class="form-group col-sm-6">
    {!! Form::label('food_allergy', __('models/products.fields.food_allergy').':') !!}
    {!! Form::text('food_allergy', null, ['class' => 'form-control']) !!}
</div>

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', __('models/products.fields.price').':') !!}
    {!! Form::text('price', null, ['class' => 'form-control']) !!}
</div>

<!-- Image Field -->
<div class="form-group col-sm-6">
    {!! Form::label('image', __('models/products.fields.image').':') !!}
    {!! Form::file('image') !!}
</div>
<div class="clearfix"></div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', __('models/products.fields.status').':') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('status', 0) !!}
        {!! Form::checkbox('status', '1', null) !!}
    </label>
</div>
<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('offer', __('models/products.fields.offer').':') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('offer', 0) !!}
        {!! Form::checkbox('offer', '1', null) !!}
    </label>
</div>
<!-- id_category Field-->
<div class="form-group col-sm-6">
    {!! Form::label('id_category', __('models/products.fields.id_category').':') !!}
        <select name="id_category" class="form-control">
            <option disabled selected>Select</option>

                @foreach($categories as $cat)
                    <option value="{{$cat->id}}" {{($products->id_category ?? '') == ($cat->id ?? '') ? 'selected' : ''}}>{{$cat->name}}</option>
                @endforeach

        </select>
</div>

<!-- id_category Field-->
<div class="form-group col-sm-6">
    {!! Form::label('id_meta', __('models/products.fields.id_meta').':') !!}
        <select name="id_metas[]" id="id_meta" class="form-control" multiple="multiple">
            <option disabled >Select</option>
            @foreach($meats as $meta)
            @php
                $selected = '';
                if(isset($products)){
                    foreach($products->id_of_metas as $ids){
                        if($ids->id_meta == $meta->id){
                            $selected = 'selected';
                        }
                    }
                }

            @endphp
                <option value="{{$meta->id}}" {{$selected}}>{{$meta->name}}</option>
            @endforeach
        </select>
</div>
<!-- related_product_ids Field-->
<div class="form-group col-sm-6">
    {!! Form::label('related_product_ids', __('models/products.fields.related_product_ids').':') !!}
        <select name="related_product_ids[]" id="related_product_ids" class="form-control" multiple="multiple">
            <option disabled >Select</option>
            @foreach($products_data as $product)
            @php
                $selected = '';
                if(isset($products) && $products->related_product_ids != null){
                    foreach($products->related_product_ids as $ids){
                        if($ids == $product->id){
                            $selected = 'selected';
                        }
                    }
                }

            @endphp
                <option value="{{$product->id}}" {{$selected}}>{{$product->name}}</option>
            @endforeach
        </select>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('products.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>
@section('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_meta').select2();
        $('#related_product_ids').select2();

        $("select").on("select2:select", function (evt) {
        var element = evt.params.data.element;
        var $element = $(element);

        $element.detach();
        $(this).append($element);
        $(this).trigger("change");
        });
    });
</script>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title')
     @lang('models/products.plural')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/products.plural')</h1>
            <div class="col-md-6">
                <input placeholder="Search product here" class="form-control" id="search-product" value="{{$search}}"/>
                <button class="btn btn-success" onclick="search()">Search</button>
                <button class="btn btn-primary" onclick="clearSearch()">Clear search</button>
            </div>
            <div class="form-group col-sm-6">
              
                    <select name="categories_ids[]" id="categories_ids" class="form-control" multiple="multiple">
                        <option disabled >Select</option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                    </select>
            </div>
            <div class="section-header-breadcrumb">
                <a href="{{ route('products.create')}}" class="btn btn-primary form-btn">@lang('crud.add_new')<i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('products.table')
            </div>
       </div>
   </div>
     @include('stisla-templates::common.paginate', ['records' => $products])
    </section>
@endsection
@section('scripts')
<script type="text/javascript">
    function search(){
        link = window.location.href
        var url = new URL(link);
        let search_value = document.getElementById('search-product');
        if(search_value.value != ''){
          
            url.searchParams.delete('search');
            url.searchParams.set('search', search_value.value);
            window.history.replaceState(null, null, url);
            window.location.reload()
        }
    }
    function clearSearch(){
      window.location.href="{{route('products.index')}}"
    }

    $(document).keyup(function (e) {
        if (e.keyCode === 13) {
         search();
        }
     })
</script>
<script type="text/javascript">
    var id_categories = {};
    $(document).ready(function() {
        $('#categories_ids').select2();

        $("select").on("select2:select", function (evt) {
            
            var element = evt.params.data.element;
            id_categories[element.value] = element.value
            
            let ids = '';
            for (const [key, value] of Object.entries(id_categories)) {
                    ids+= '-'+value
            }
            link = window.location.href;
            var url = new URL(link);
            let search_value = document.getElementById('search-product');
            if(ids != ''){

                url.searchParams.delete('ids');
                url.searchParams.set('ids', ids);
                window.history.replaceState(null, null, url);
            }
            
            var $element = $(element);
            $element.detach();
            $(this).append($element);
            $(this).trigger("change");
        });
    });
</script>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('title')
    @lang('models/products.singular')  @lang('crud.details') 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>@lang('models/products.singular') @lang('crud.details')</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('products.index') }}"
                 class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('products.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/products/table.blade.php
<div class="table-responsive">
    <table class="table" id="products-table">
        <thead>
            <tr>
                <th>@lang('models/products.fields.name')</th>
                <th>@lang('models/products.fields.description')</th>
                <th>@lang('models/products.fields.food_allergy')</th>
                <th>@lang('models/products.fields.price')</th>
                <th>@lang('models/products.fields.id_category')</th>
                <th>@lang('models/products.fields.image')</th>
                <th>@lang('models/products.fields.status')</th>
                <th colspan="3">@lang('crud.action')</th>
            </tr>
        </thead>
        <tbody>
        @foreach($products as $products)
            <tr>
                       <td>{{ $products->name }}</td>
            <td>{{ $products->description }}</td>
            <td>{{ $products->food_allergy }}</td>
            <td>{{ $products->price }}</td>
            <td>{{ $products->category->name ?? 'N/A' }}</td>
            <td><img   onerror="this.src='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg'" class="image-preview" src="{{asset('images/'.$products->image)}}" /></td>
            <td>{{ $products->status == '1' ? 'ON' : 'OFF'}}</td>
                       <td class=" text-center">
                           {!! Form::open(['route' => ['products.destroy', $products->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('products.show', [$products->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('products.edit', [$products->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                   </tr>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>