routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/forgot-password', function () {
  return view('auth.forgot-password');
})->middleware('guest')->name('password.request');
Route::get('/reset-password/{token}', function ($token) {
  return view('auth.reset-password', ['token' => $token]);
})->middleware('guest')->name('password.reset');
Auth::routes();
Route::get('/admin/login', [App\Http\Controllers\HomeController::class, 'adminLogin'])->name('admin.login');
Route::post('/admin/login/request', [App\Http\Controllers\HomeController::class, 'adminLoginRequest'])->name('admin.login.request');
Route::post('/admin/logout', [App\Http\Controllers\HomeController::class, 'adminLogout'])->name('admin.logut');
Route::middleware(['admin.auth'])->group( function () {
  Route::group(['prefix' => 'admin'], function(){

    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('admin');
    Route::post('/admin-edit-profile', [App\Http\Controllers\HomeController::class, 'adminEditProfile'])->name('admin.edit.profile');
    Route::post('/admin-edit-password', [App\Http\Controllers\HomeController::class, 'adminEditPassword'])->name('admin.edit.password');
    Route::resource('generalSettings', App\Http\Controllers\generalSettingsController::class);
    Route::resource('resturentAddresses', App\Http\Controllers\ResturentAddressController::class);
    Route::get('resturentAddresses-add/{id?}', [App\Http\Controllers\ResturentAddressController::class,'addResturentAddress'])->name('resturentAddresses.add-address');

    Route::post('save-address-of_resturent', [App\Http\Controllers\ResturentAddressController::class,'saveResturentAddress'])->name('resturentAddresses.save-address');

    Route::resource('deliveryChargesDetails', App\Http\Controllers\deliveryChargesDetailsController::class);
    Route::resource('orders', App\Http\Controllers\ordersController::class);
    Route::resource('sliders', App\Http\Controllers\sliderController::class);
    Route::resource('ourStories', App\Http\Controllers\ourStoryController::class);
    Route::resource('galleries', App\Http\Controllers\GalleryController::class);
    Route::resource('cms', App\Http\Controllers\CmsController::class);
    Route::resource('smsSettings', App\Http\Controllers\SmsSettingController::class);
    Route::resource('messageTemplatings', App\Http\Controllers\MessageTemplatingController::class);
    Route::resource('tableReservations', App\Http\Controllers\TableReservationController::class);
    Route::get('page-builder', [App\Http\Controllers\PageBuilderController::class,'index'])->name('page-builder');
    Route::resource('categories', App\Http\Controllers\categoryController::class);
    Route::post('save.php', [App\Http\Controllers\PageBuilderController::class,'save']);
    Route::post('upload.php', [App\Http\Controllers\PageBuilderController::class,'upload']);
    Route::get('scan.php', [App\Http\Controllers\PageBuilderController::class,'scan']);
    Route::resource('pages', App\Http\Controllers\PagesController::class);
    Route::resource('products', App\Http\Controllers\ProductsController::class);
    Route::resource('productMetas', App\Http\Controllers\product_metaController::class);
    Route::post('add-attribute', [App\Http\Controllers\product_metaController::class,'addAttribute'])->name('add-attribute');
    Route::post('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes'])->name('fetch-attributes');

    Route::get('add-child-product-meta/{id_meta}', [App\Http\Controllers\product_metaController::class,'addChildProductMeta'])->name('add-child-product-meta');
    Route::post('delete-product-meta-attribute/{id?}', [App\Http\Controllers\product_metaController::class,'deleteProductMetaAttribute'])->name('delete-product-meta-attribute');
    Route::post('update-attribute', [App\Http\Controllers\product_metaController::class,'updateAttributeForAdmin'])->name('update-attribute');
    Route::resource('resturentTimings', App\Http\Controllers\ResturentTimingsController::class);
    Route::resource('restaurantTimingsSpecifics', App\Http\Controllers\RestaurantTimingsSpecificController::class);
    Route::resource('paymentMethods', App\Http\Controllers\PaymentMethodsController::class);
    Route::resource('reviews', App\Http\Controllers\ReviewsController::class);
    Route::resource('users', App\Http\Controllers\UsersController::class);
    Route::get('users/orders/{id}', [App\Http\Controllers\UsersController::class,'showOrders'])->name('users.view.orders');
    Route::get('users/carts/{id}', [App\Http\Controllers\UsersController::class,'showCarts'])->name('users.view.carts');
    Route::resource('tableCategories', App\Http\Controllers\TableCategoriesController::class);
    Route::resource('customerReservations', App\Http\Controllers\CustomerReservationsController::class);

    Route::resource('locations', App\Http\Controllers\LocationsController::class);


    Route::resource('locationsAttributes', App\Http\Controllers\LocationsAttributesController::class);
    Route::get('reset-cache', [App\Http\Controllers\DashboardController::class,'resetCache'])->name('reset-cache');
  });
});


Route::get('my-account', [App\Http\Controllers\HomeController::class, 'myAccount'])->name('user.my-account');
Route::get('change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('user.change.password');
Route::post('user-details-update', [App\Http\Controllers\HomeController::class, 'userDetailsUpdate'])->name('user-details-update');
Route::post('user-registration', [App\Http\Controllers\HomeController::class, 'userRegister'])->name('user-registration');
Route::post('user-password-update', [App\Http\Controllers\HomeController::class, 'userPasswordUpdate'])->name('user.password.update');

Route::get('order-history', [App\Http\Controllers\HomeController::class, 'orderHistory'])->name('user.order.history');
Route::get('addresses', [App\Http\Controllers\HomeController::class, 'userAddresses'])->name('user.addresses');

Route::get('/', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('page/{name}', [App\Http\Controllers\PageBuilderController::class,'getPage'])->name('pages');

Route::get('order-online', [App\Http\Controllers\HomeController::class,'OrderOnline'])->name('order-online');
Route::get('payment-confirm', [App\Http\Controllers\HomeController::class,'paymentConfirm'])->name('payment-confirm');

Route::get('thank-you', [App\Http\Controllers\HomeController::class,'thankYou'])->name('thank-you');
Route::get('contact-us', [App\Http\Controllers\HomeController::class,'contactUs'])->name('contact-us');
Route::get('checkout/{reference?}', [App\Http\Controllers\HomeController::class,'checkout'])->name('checkout');
Route::post('place-order', [App\Http\Controllers\HomeController::class,'placeOrder'])->name('web.place-order');
Route::get('reviews/{ratings?}', [App\Http\Controllers\HomeController::class,'reviews'])->name('reviews');

Route::get('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes']);


Route::resource('notifications', App\Http\Controllers\NotificationsController::class);
Route::post('stream-check-out', [App\Http\Controllers\PaymentMethodsController::class,'cardStreamCallback']);
Route::post('get-cart-id', [App\Http\Controllers\HomeController::class,'getCartId'])->name('get-cart-id');


Route::resource('vouchers', App\Http\Controllers\VouchersController::class);
Route::get('download/pdf/{reference}', [App\Http\Controllers\HomeController::class,'downloadPdf'])->name('downloadPdf');
Route::get('save/pdf/{reference}', [App\Http\Controllers\HomeController::class,'savePdf'])->name('savePdf');
Route::get('view/pdf/{reference}', [App\Http\Controllers\HomeController::class,'viewPdf'])->name('viewPdf');


Route::get('reservations',[App\Http\Controllers\HomeController::class,'reservations'])->name('reservations');
Route::get('locations',[App\Http\Controllers\HomeController::class,'locations'])->name('locations');
Route::get('locations/{id}',[App\Http\Controllers\HomeController::class,'locations'])->name('locations.attributes');











Route::resource('holdCarts', App\Http\Controllers\HoldCartsController::class);


Route::resource('caosGenralSettings', App\Http\Controllers\CaosGenralSettingsController::class);

resources/views/pages/create.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.add_new') @lang('models/pages.singular')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/pages.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('pages.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'pages.store', 'files' => true]) !!}
                                    <div class="row">
                                        @include('pages.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
<script type="text/javascript">
    $('#html_area').hide();
    $('#page_type').change(function(){
        let select = $(this).val();
        if(select =='static'){
            $('#page_template_name_area').show();
            $('#html_area').hide();
        }

        if(select == 'dynamic'){
            $('#page_template_name_area').hide();
            $('#html_area').hide();
        }
        if(select =='informative'){
            $('#page_template_name_area').hide();
            $('#html_area').show();
        }
    });
    $('#background_type').change(function(){
        let type = $(this).val();
        if(type != 'no_background'){
            $('#background_area').html('')
            if(type == 'color'){
                $('#background_area').append(`
                    
                    <label for="background_type_value">Color:</label>
                    <input class="form-control" name="background_type_value" type="text" id="background_type_value">

                `)    
            }
            if(type == 'image'){
                $('#background_area').append(`
                    
                    <label for="background_type_value">Image:</label>
                    <input class="form-control" name="background_type_value" type="file" id="background_type_value">

                `)    
            }
            $('#background_area').removeClass('d-none');


        }else{
            $('#background_area').addClass('d-none');
        }
    });


</script>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.edit') @lang('models/pages.singular')
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/pages.singular')</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('pages.index') }}"  class="btn btn-primary">@lang('crud.back')</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($pages, ['route' => ['pages.update', $pages->id], 'method' => 'patch', 'files' => true]) !!}
                                        <div class="row">
                                            @include('pages.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection
@section('scripts')
<script type="text/javascript">
    var selection = "{{$pages->page_type}}";
    if(selection =='static'){
        $('#page_template_name_area').show();
        $('#html_area').hide();
    }
    if(selection == 'dynamic'){
        $('#page_template_name_area').hide();
        $('#html_area').hide();
    }else{
        $('#page_template_name_area').hide();
        $('#html_area').show();
    }
    $('#page_type').change(function(){
        let select = $(this).val();
        if(select =='static'){
            $('#page_template_name_area').show();
            $('#html_area').hide();
        }

        if(select == 'dynamic'){
            $('#page_template_name_area').hide();
            $('#html_area').hide();
        }
        if(select =='informative'){
            $('#page_template_name_area').hide();
            $('#html_area').show();
        }
    });
     var background_type = "{{$pages->background_type}}";
     var background_type_value = "{{$pages->background_type_value}}";
     if(background_type != 'no_background'){
        $('#background_area').html('')
        if(background_type == 'color'){
            $('#background_area').append(`
                
                <label for="background_type_value">Color:</label>
                <input class="form-control" name="background_type_value" type="text" id="background_type_value" value="${background_type_value}">

            `)    
        }
        if(background_type == 'image'){
            $('#background_area').append(`
                
                <label for="background_type_value">Image:</label>
                <input class="form-control" name="background_type_value" type="file" id="background_type_value">

            `)    
        }
        $('#background_area').removeClass('d-none');


    }else{
        $('#background_area').addClass('d-none');
    }



    $('#background_type').change(function(){
        let type = $(this).val();
        if(type != 'no_background'){
            $('#background_area').html('')
            if(type == 'color'){
                $('#background_area').append(`
                    
                    <label for="background_type_value">Color:</label>
                    <input class="form-control" name="background_type_value" type="text" id="background_type_value">

                `)    
            }
            if(type == 'image'){
                $('#background_area').append(`
                    
                    <label for="background_type_value">Image:</label>
                    <input class="form-control" name="background_type_value" type="file" id="background_type_value">

                `)    
            }
            $('#background_area').removeClass('d-none');


        }else{
            $('#background_area').addClass('d-none');
        }
    });


</script>
@endsection

resources/views/pages/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/pages.fields.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', __('models/pages.fields.type').':') !!}
    <select name="type" class="form-control">
        @foreach(App\Models\Pages::TYPES as $type)
            <option value="{{$type}}">{{ucfirst($type)}}</option>
        @endforeach
    </select>
</div>

<!-- page_type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('page_type', __('models/pages.fields.page_type').':') !!}
    @php 
        $selected = '';

    @endphp
    <select name="page_type" class="form-control" id="page_type">
        @foreach(App\Models\Pages::PAGE_TYPES as $page_type)
            @php  
                if(isset($pages->page_type) && $pages->page_type == $page_type){
                    $selected = 'selected';
                } 

            @endphp
            <option value="{{$page_type}}" {{$selected}}>{{ucfirst($page_type)}}</option>
        @endforeach
    </select>
</div>

<!-- template Field -->
<div class="form-group col-sm-6" id="page_template_name_area">
    {!! Form::label('template', __('models/pages.fields.template').':') !!}
    <select name="page_template_name" class="form-control" id="page_template_name">
        @foreach(App\Models\Pages::PAGE_TEMPLATES as $template)
            <option value="{{$template}}">{{ucfirst($template)}}</option>
        @endforeach
    </select>
</div>


<!-- background_type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('background_type', __('models/pages.fields.background_type').':') !!}
    @php 
        $bg_selected = '';

    @endphp

    <select name="background_type" class="form-control" id="background_type">
        @foreach(App\Models\Pages::BACKGROUND_TYPE as $background_type)
            @php  
                if(isset($pages->background_type) && $pages->background_type == $background_type){
                    $bg_selected = 'selected';
                } 
            @endphp
            <option value="{{$background_type}}" {{$bg_selected}}>{{ucfirst(str_replace('_', ' ', $background_type))}}</option>
        @endforeach
    </select>
</div>
<!-- background_type Field -->
<div class="form-group col-sm-6 d-none" id="background_area">
</div>




<!-- template Field -->
<div class="form-group col-sm-6" id="html_area">
    {!! Form::label('template', __('models/pages.fields.template').':') !!}
    <textarea id="wysiwg-textarea" name="html">{{isset($pages->html) ? $pages->html : ''}}</textarea>
</div>




<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('pages.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>

resources/views/pages/index.blade.php
@extends('layouts.app')
@section('title')
     @lang('models/pages.plural')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/pages.plural')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('pages.create')}}" class="btn btn-primary form-btn">@lang('crud.add_new')<i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('pages.table')
            </div>
       </div>
   </div>
    
    </section>
@endsection

resources/views/pages/show.blade.php
@extends('layouts.app')
@section('title')
    @lang('models/pages.singular')  @lang('crud.details') 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>@lang('models/pages.singular') @lang('crud.details')</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('pages.index') }}"
                 class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('pages.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/pages/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', __('models/pages.fields.name').':') !!}
    <p>{{ $pages->name }}</p>
</div>

<!-- Html Field -->
<div class="form-group">
    {!! Form::label('html', __('models/pages.fields.html').':') !!}
    <p>{{ $pages->html }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/pages.fields.created_at').':') !!}
    <p>{{ $pages->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', __('models/pages.fields.updated_at').':') !!}
    <p>{{ $pages->updated_at }}</p>
</div>

resources/views/pages/table.blade.php
<div class="table-responsive">
    <table class="table" id="pages-table">
        <thead>
            <tr>
                <th>@lang('models/pages.fields.name')</th>
        
                <th colspan="3">@lang('crud.action')</th>
            </tr>
        </thead>
        <tbody>
        @foreach($pages as $page)
            <tr>
                       <td>{{ $page->name }}</td>
           
                       <td class=" text-center">
                           {!! Form::open(['route' => ['pages.destroy', $page->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('page-builder') !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               @if($page->page_type == 'static')
                                <a href="{!! route('page-builder') !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               @endif
                               @if($page->page_type == 'dynamic' || $page->page_type == 'informative')
                               
                                <a href="{!! route('pages.edit',[$page->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               @endif


                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                   </tr>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>