routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/forgot-password', function () {
  return view('auth.forgot-password');
})->middleware('guest')->name('password.request');
Route::get('/reset-password/{token}', function ($token) {
  return view('auth.reset-password', ['token' => $token]);
})->middleware('guest')->name('password.reset');
Auth::routes();
Route::get('/admin/login', [App\Http\Controllers\HomeController::class, 'adminLogin'])->name('admin.login');
Route::post('/admin/login/request', [App\Http\Controllers\HomeController::class, 'adminLoginRequest'])->name('admin.login.request');
Route::post('/admin/logout', [App\Http\Controllers\HomeController::class, 'adminLogout'])->name('admin.logut');
Route::middleware(['admin.auth'])->group( function () {
  Route::group(['prefix' => 'admin'], function(){

    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('admin');
    Route::post('/admin-edit-profile', [App\Http\Controllers\HomeController::class, 'adminEditProfile'])->name('admin.edit.profile');
    Route::post('/admin-edit-password', [App\Http\Controllers\HomeController::class, 'adminEditPassword'])->name('admin.edit.password');
    Route::resource('generalSettings', App\Http\Controllers\generalSettingsController::class);
    Route::resource('resturentAddresses', App\Http\Controllers\ResturentAddressController::class);
    Route::get('resturentAddresses-add/{id?}', [App\Http\Controllers\ResturentAddressController::class,'addResturentAddress'])->name('resturentAddresses.add-address');

    Route::post('save-address-of_resturent', [App\Http\Controllers\ResturentAddressController::class,'saveResturentAddress'])->name('resturentAddresses.save-address');

    Route::resource('deliveryChargesDetails', App\Http\Controllers\deliveryChargesDetailsController::class);
    Route::resource('orders', App\Http\Controllers\ordersController::class);
    Route::resource('sliders', App\Http\Controllers\sliderController::class);
    Route::resource('ourStories', App\Http\Controllers\ourStoryController::class);
    Route::resource('galleries', App\Http\Controllers\GalleryController::class);
    Route::resource('cms', App\Http\Controllers\CmsController::class);
    Route::resource('smsSettings', App\Http\Controllers\SmsSettingController::class);
    Route::resource('messageTemplatings', App\Http\Controllers\MessageTemplatingController::class);
    Route::resource('tableReservations', App\Http\Controllers\TableReservationController::class);
    Route::get('page-builder', [App\Http\Controllers\PageBuilderController::class,'index'])->name('page-builder');
    Route::resource('categories', App\Http\Controllers\categoryController::class);
    Route::post('save.php', [App\Http\Controllers\PageBuilderController::class,'save']);
    Route::post('upload.php', [App\Http\Controllers\PageBuilderController::class,'upload']);
    Route::get('scan.php', [App\Http\Controllers\PageBuilderController::class,'scan']);
    Route::resource('pages', App\Http\Controllers\PagesController::class);
    Route::resource('products', App\Http\Controllers\ProductsController::class);
    Route::resource('productMetas', App\Http\Controllers\product_metaController::class);
    Route::post('add-attribute', [App\Http\Controllers\product_metaController::class,'addAttribute'])->name('add-attribute');
    Route::post('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes'])->name('fetch-attributes');

    Route::get('add-child-product-meta/{id_meta}', [App\Http\Controllers\product_metaController::class,'addChildProductMeta'])->name('add-child-product-meta');
    Route::post('delete-product-meta-attribute/{id?}', [App\Http\Controllers\product_metaController::class,'deleteProductMetaAttribute'])->name('delete-product-meta-attribute');
    Route::post('update-attribute', [App\Http\Controllers\product_metaController::class,'updateAttributeForAdmin'])->name('update-attribute');
    Route::resource('resturentTimings', App\Http\Controllers\ResturentTimingsController::class);
    Route::resource('restaurantTimingsSpecifics', App\Http\Controllers\RestaurantTimingsSpecificController::class);
    Route::resource('paymentMethods', App\Http\Controllers\PaymentMethodsController::class);
    Route::resource('reviews', App\Http\Controllers\ReviewsController::class);
    Route::resource('users', App\Http\Controllers\UsersController::class);
    Route::get('users/orders/{id}', [App\Http\Controllers\UsersController::class,'showOrders'])->name('users.view.orders');
    Route::get('users/carts/{id}', [App\Http\Controllers\UsersController::class,'showCarts'])->name('users.view.carts');
    Route::resource('tableCategories', App\Http\Controllers\TableCategoriesController::class);
    Route::resource('customerReservations', App\Http\Controllers\CustomerReservationsController::class);

    Route::resource('locations', App\Http\Controllers\LocationsController::class);


    Route::resource('locationsAttributes', App\Http\Controllers\LocationsAttributesController::class);
    Route::get('reset-cache', [App\Http\Controllers\DashboardController::class,'resetCache'])->name('reset-cache');
  });
});


Route::get('my-account', [App\Http\Controllers\HomeController::class, 'myAccount'])->name('user.my-account');
Route::get('change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('user.change.password');
Route::post('user-details-update', [App\Http\Controllers\HomeController::class, 'userDetailsUpdate'])->name('user-details-update');
Route::post('user-registration', [App\Http\Controllers\HomeController::class, 'userRegister'])->name('user-registration');
Route::post('user-password-update', [App\Http\Controllers\HomeController::class, 'userPasswordUpdate'])->name('user.password.update');

Route::get('order-history', [App\Http\Controllers\HomeController::class, 'orderHistory'])->name('user.order.history');
Route::get('addresses', [App\Http\Controllers\HomeController::class, 'userAddresses'])->name('user.addresses');

Route::get('/', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'home'])->name('home-page');
Route::get('page/{name}', [App\Http\Controllers\PageBuilderController::class,'getPage'])->name('pages');

Route::get('order-online', [App\Http\Controllers\HomeController::class,'OrderOnline'])->name('order-online');
Route::get('payment-confirm', [App\Http\Controllers\HomeController::class,'paymentConfirm'])->name('payment-confirm');

Route::get('thank-you', [App\Http\Controllers\HomeController::class,'thankYou'])->name('thank-you');
Route::get('contact-us', [App\Http\Controllers\HomeController::class,'contactUs'])->name('contact-us');
Route::get('checkout/{reference?}', [App\Http\Controllers\HomeController::class,'checkout'])->name('checkout');
Route::post('place-order', [App\Http\Controllers\HomeController::class,'placeOrder'])->name('web.place-order');
Route::get('reviews/{ratings?}', [App\Http\Controllers\HomeController::class,'reviews'])->name('reviews');

Route::get('fetch-attributes', [App\Http\Controllers\product_metaController::class,'fetchAttributes']);


Route::resource('notifications', App\Http\Controllers\NotificationsController::class);
Route::post('stream-check-out', [App\Http\Controllers\PaymentMethodsController::class,'cardStreamCallback']);
Route::post('get-cart-id', [App\Http\Controllers\HomeController::class,'getCartId'])->name('get-cart-id');


Route::resource('vouchers', App\Http\Controllers\VouchersController::class);
Route::get('download/pdf/{reference}', [App\Http\Controllers\HomeController::class,'downloadPdf'])->name('downloadPdf');
Route::get('save/pdf/{reference}', [App\Http\Controllers\HomeController::class,'savePdf'])->name('savePdf');
Route::get('view/pdf/{reference}', [App\Http\Controllers\HomeController::class,'viewPdf'])->name('viewPdf');


Route::get('reservations',[App\Http\Controllers\HomeController::class,'reservations'])->name('reservations');
Route::get('locations',[App\Http\Controllers\HomeController::class,'locations'])->name('locations');
Route::get('locations/{id}',[App\Http\Controllers\HomeController::class,'locations'])->name('locations.attributes');











Route::resource('holdCarts', App\Http\Controllers\HoldCartsController::class);


Route::resource('caosGenralSettings', App\Http\Controllers\CaosGenralSettingsController::class);

app/Models/CustomerReservation.php
<?php

namespace App\Data\Models;

use Illuminate\Database\Eloquent\Model;

class CustomerReservation extends Model
{
    const Birthday     = 1;
    const Anniversary  = 2;
    const DateNight    = 3;
    const BusinessMeal = 4;
    const Celebration  = 5;

    protected $table = 'customer_reservation';

    protected $fillable = ["firstname", "lastname", "phone", "email", "booking_date", "persons", "booking_time", 
    "special_occasion", "special_request", "restaurant_newsletter", "opentable_newsletter", "reservations_reminder"];

}

app/Models/CustomerReservations.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class CustomerReservations
 * @package App\Models
 * @version May 12, 2022, 10:56 pm UTC
 *
 * @property string $firstname
 * @property string $lastname
 * @property string $phone
 * @property string $email
 * @property string $booking_date
 * @property integer $persons
 * @property string $status
 */
class CustomerReservations extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'customer_reservation';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'firstname',
        'lastname',
        'phone',
        'email',
        'booking_date',
        'persons',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'firstname' => 'string',
        'lastname' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'booking_date' => 'string',
        'persons' => 'integer',
        'status' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'firstname' => 'required',
        'lastname' => 'required',
        'phone' => 'required',
        'email' => 'required',
        'booking_date' => 'required',
        'persons' => 'required',
        'status' => 'required'
    ];

    
}

app/Http/Controllers/CustomerReservationsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCustomerReservationsRequest;
use App\Http\Requests\UpdateCustomerReservationsRequest;
use App\Repositories\CustomerReservationsRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\CustomerReservations;
use Illuminate\Http\Request;
use Flash;
use Response;

class CustomerReservationsController extends AppBaseController
{
    /** @var  CustomerReservationsRepository */
    private $customerReservationsRepository;

    public function __construct(CustomerReservationsRepository $customerReservationsRepo)
    {
        $this->customerReservationsRepository = $customerReservationsRepo;
    }

    /**
     * Display a listing of the CustomerReservations.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $customerReservations =CustomerReservations::orderBy('id','desc')->get();

        return view('customer_reservations.index')
            ->with('customerReservations', $customerReservations);
    }

    /**
     * Show the form for creating a new CustomerReservations.
     *
     * @return Response
     */
    public function create()
    {
        return view('customer_reservations.create');
    }

    /**
     * Store a newly created CustomerReservations in storage.
     *
     * @param CreateCustomerReservationsRequest $request
     *
     * @return Response
     */
    public function store(CreateCustomerReservationsRequest $request)
    {
        $input = $request->all();

        $customerReservations = $this->customerReservationsRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/customerReservations.singular')]));

        return redirect(route('customerReservations.index'));
    }

    /**
     * Display the specified CustomerReservations.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $customerReservations = $this->customerReservationsRepository->find($id);

        if (empty($customerReservations)) {
            Flash::error(__('messages.not_found', ['model' => __('models/customerReservations.singular')]));

            return redirect(route('customerReservations.index'));
        }

        return view('customer_reservations.show')->with('customerReservations', $customerReservations);
    }

    /**
     * Show the form for editing the specified CustomerReservations.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $customerReservations = $this->customerReservationsRepository->find($id);

        if (empty($customerReservations)) {
            Flash::error(__('messages.not_found', ['model' => __('models/customerReservations.singular')]));

            return redirect(route('customerReservations.index'));
        }

        return view('customer_reservations.edit')->with('customerReservations', $customerReservations);
    }

    /**
     * Update the specified CustomerReservations in storage.
     *
     * @param int $id
     * @param UpdateCustomerReservationsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCustomerReservationsRequest $request)
    {
        $customerReservations = $this->customerReservationsRepository->find($id);

        if (empty($customerReservations)) {
            Flash::error(__('messages.not_found', ['model' => __('models/customerReservations.singular')]));

            return redirect(route('customerReservations.index'));
        }

        $customerReservations = $this->customerReservationsRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/customerReservations.singular')]));

        return redirect(route('customerReservations.index'));
    }

    /**
     * Remove the specified CustomerReservations from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $customerReservations = $this->customerReservationsRepository->find($id);

        if (empty($customerReservations)) {
            Flash::error(__('messages.not_found', ['model' => __('models/customerReservations.singular')]));

            return redirect(route('customerReservations.index'));
        }

        $this->customerReservationsRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/customerReservations.singular')]));

        return redirect(route('customerReservations.index'));
    }
}

resources/views/customer_reservations/create.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.add_new') @lang('models/customerReservations.singular')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/customerReservations.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('customerReservations.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'customerReservations.store']) !!}
                                    <div class="row">
                                        @include('customer_reservations.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/customer_reservations/edit.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.edit') @lang('models/customerReservations.singular')
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/customerReservations.singular')</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('customerReservations.index') }}"  class="btn btn-primary">@lang('crud.back')</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($customerReservations, ['route' => ['customerReservations.update', $customerReservations->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('customer_reservations.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/customer_reservations/fields.blade.php
<!-- Firstname Field -->
<div class="form-group col-sm-6">
    {!! Form::label('firstname', __('models/customerReservations.fields.firstname').':') !!}
    {!! Form::text('firstname', null, ['class' => 'form-control']) !!}
</div>

<!-- Lastname Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lastname', __('models/customerReservations.fields.lastname').':') !!}
    {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', __('models/customerReservations.fields.phone').':') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', __('models/customerReservations.fields.email').':') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Booking Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('booking_date', __('models/customerReservations.fields.booking_date').':') !!}
    {!! Form::text('booking_date', null, ['class' => 'form-control']) !!}
</div>

<!-- Persons Field -->
<div class="form-group col-sm-6">
    {!! Form::label('persons', __('models/customerReservations.fields.persons').':') !!}
    {!! Form::number('persons', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', __('models/customerReservations.fields.status').':') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('customerReservations.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>

resources/views/customer_reservations/index.blade.php
@extends('layouts.app')
@section('title')
     @lang('models/customerReservations.plural')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/customerReservations.plural')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('customerReservations.create')}}" class="btn btn-primary form-btn">@lang('crud.add_new')<i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('customer_reservations.table')
            </div>
       </div>
   </div>
    
    </section>
@endsection

resources/views/customer_reservations/show.blade.php
@extends('layouts.app')
@section('title')
    @lang('models/customerReservations.singular')  @lang('crud.details') 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>@lang('models/customerReservations.singular') @lang('crud.details')</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('customerReservations.index') }}"
                 class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('customer_reservations.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/customer_reservations/show_fields.blade.php
<!-- Firstname Field -->
<div class="form-group">
    {!! Form::label('firstname', __('models/customerReservations.fields.firstname').':') !!}
    <p>{{ $customerReservations->firstname }}</p>
</div>

<!-- Lastname Field -->
<div class="form-group">
    {!! Form::label('lastname', __('models/customerReservations.fields.lastname').':') !!}
    <p>{{ $customerReservations->lastname }}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', __('models/customerReservations.fields.phone').':') !!}
    <p>{{ $customerReservations->phone }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', __('models/customerReservations.fields.email').':') !!}
    <p>{{ $customerReservations->email }}</p>
</div>

<!-- Booking Date Field -->
<div class="form-group">
    {!! Form::label('booking_date', __('models/customerReservations.fields.booking_date').':') !!}
    <p>{{ $customerReservations->booking_date }}</p>
</div>

<!-- Persons Field -->
<div class="form-group">
    {!! Form::label('persons', __('models/customerReservations.fields.persons').':') !!}
    <p>{{ $customerReservations->persons }}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', __('models/customerReservations.fields.status').':') !!}
    <p>{{ $customerReservations->status }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/customerReservations.fields.created_at').':') !!}
    <p>{{ $customerReservations->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', __('models/customerReservations.fields.updated_at').':') !!}
    <p>{{ $customerReservations->updated_at }}</p>
</div>

resources/views/customer_reservations/table.blade.php
<div class="table-responsive">
    <table class="table" id="customerReservations-table">
        <thead>
            <tr>
                <th>@lang('models/customerReservations.fields.firstname')</th>
        <th>@lang('models/customerReservations.fields.lastname')</th>
        <th>@lang('models/customerReservations.fields.phone')</th>
        <th>@lang('models/customerReservations.fields.email')</th>
        <th>@lang('models/customerReservations.fields.booking_date')</th>
        <th>@lang('models/customerReservations.fields.booking_time')</th>
        <th>@lang('models/customerReservations.fields.persons')</th>
        <th>@lang('models/customerReservations.fields.status')</th>
                <th colspan="3">@lang('crud.action')</th>
            </tr>
        </thead>
        <tbody>
        @foreach($customerReservations as $customerReservations)
            <tr>
                       <td>{{ $customerReservations->firstname }}</td>
            <td>{{ $customerReservations->lastname }}</td>
            <td>{{ $customerReservations->phone }}</td>
            <td>{{ $customerReservations->email }}</td>
            <td>{{ date('Y-m-d', strtotime($customerReservations->booking_date)) }}</td>
            <td>{{ $customerReservations->booking_time }}</td>
            <td>{{ $customerReservations->persons }}</td>
            <td>{{ $customerReservations->status }}</td>
                        <td class=" text-center">
                           {!! Form::open(['route' => ['customerReservations.destroy', $customerReservations->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('customerReservations.show', [$customerReservations->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('customerReservations.edit', [$customerReservations->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
                           </div> 
                           {!! Form::close() !!}
                       </td>
                   </tr>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>